services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: fishing
      POSTGRES_PASSWORD: F1shApp92Zp4Lts
      POSTGRES_DB: fishing
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://fishing:F1shApp92Zp4Lts@db:5432/fishing?schema=public"
      NODE_ENV: production
    ports:
      - "3000:3000"
    command: sh -c "npx prisma migrate deploy && npm start"
volumes:
  db_data: