export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import Header from '../components/Header';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
